name: KMeans Clustering Webpage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.12"

    - name: Install dependencies using Makefile
      run: |
        make install

    - name: Run the web application
      run: |
        make run &
        sleep 10  # Give the server time to start

    - name: Verify server is running
      run: curl -I http://localhost:3000
